services:
  dockge:
    image: louislam/dockge:1
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /home/null/dockge/stacks:/home/null/dockge/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/home/null/dockge/stacks
    restart: unless-stopped